services:
  nginx:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/src
      - vendor_data:/var/www/vendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src:/var/www/src
      - vendor_data:/var/www/vendor
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file: ".env"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  vendor_data:
